### PR TITLE
Remove annotation attribute duplicated from OpenIdProviderMetadata

### PR DESCRIPTION
**Pull request by pdudits**

### CODE REVIEW

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by Pandrex247** [comment]
This breaks compilation

**Comment by Pandrex247** [comment]
```
[ERROR] /C:/Users/pandr/Git/ecosystem-security-connectors/openid/src/main/java/fish/payara/security/openid/GoogleDefinitionConverter.java:[166,13] method does not override or implement a method from a supertype
[ERROR] /C:/Users/pandr/Git/ecosystem-security-connectors/openid/src/main/java/fish/payara/security/openid/AzureDefinitionConverter.java:[178,13] method does not override or implement a method from a supertype
```

**Comment by pdudits** [comment]
Yes, I noticed too late, new PR coming up

**Pull request merged**
