### PR TITLE
Add client authentication "client_secret_basic"

### PR DESCRIPTION
**Pull request by miguelborges99**
Current implementation only supports one client authentication, i.e. "client_secret_post". This pull request adds the "client_secret_basic" client authentication. OpenID Connect Specification, specifies "client_secret_basic" as the default client authentication.  For more details, check https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

### CODE REVIEW

**Comment by jGauravGupta** [comment]
Hi @miguelborges99,

Thanks for the PR.  Can you fix the conflicts and rebase the PR.

**Comment by miguelborges99** [comment]
> Hi @miguelborges99,
> 
> Thanks for the PR. Can you fix the conflicts and rebase the PR.

Hi, the conflicts have been solved

**Comment by exi** [comment]
This missing feature prevents us from using the openid connect implementation.
Is there any progress here, since it's a shame that payara does not support the default auth method.

**Comment by miguelborges99** [comment]
> This missing feature prevents us from using the openid connect implementation. Is there any progress here, since it's a shame that payara does not support the default auth method.

I've been trying to introduce this simple feature in payara, for quite a long time, thinking with this contribution, I could add and extend the code to other client authentications. But, since there is no feedback, I assume that this is not important or payara wants to do it in another way...

**Pull request closed without merging**
