### PR TITLE
FISH-5941 pom version increased

### PR DESCRIPTION
**Pull request by luiseufrasio**
version updated after deploy in maven central

### CODE REVIEW

**Comment by luiseufrasio** [comment]
Jenkins test please

**Comment by kalinchan** [comment]
I believe this can be closed?

**Comment by Pandrex247** [comment]
This is out of order.
It should have been merged before https://github.com/payara/ecosystem-security-connectors/pull/183 and a tag created.

**Comment by Pandrex247** [comment]
@luiseufrasio let me know if you need some help unpicking this.
What we probably need to do is either revert #183, merge this, create a tag at the new HEAD of master (which should be #178 with this applied on top), and then remerge #183. 
Alternatively we can have a dangling tag and check out commit [3ab9fc1662389f1f4ab5105ef75ac2d4ecffdc5c](https://github.com/payara/ecosystem-security-connectors/commit/3ab9fc1662389f1f4ab5105ef75ac2d4ecffdc5c), apply this PR on top of it, and then create & push a tag for 2.3.0 - no reversions necessary and we can then drop this PR.

**Pull request closed without merging**
